-- Fictional equity plan administration schema.
-- Share quantities are explicit DECIMAL(18,4) share counts; never use float.

CREATE TABLE grants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_name      VARCHAR(120) NOT NULL,
    grantee         VARCHAR(120) NOT NULL,
    grant_date      DATE         NOT NULL,
    total_quantity  NUMERIC(18,4) NOT NULL CHECK (total_quantity > 0),
    cliff_months    INTEGER      NOT NULL CHECK (cliff_months >= 0),
    vesting_months  INTEGER      NOT NULL CHECK (vesting_months > 0),
    plan_name       VARCHAR(160) NOT NULL
);

CREATE TABLE vesting_nodes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id             BIGINT       NOT NULL REFERENCES grants(id),
    seq_no               INTEGER      NOT NULL,
    vest_date            DATE         NOT NULL,
    scheduled_quantity   NUMERIC(18,4) NOT NULL CHECK (scheduled_quantity >= 0),
    cliff_node           BOOLEAN      NOT NULL,
    conditional_flag     BOOLEAN      NOT NULL,
    condition_met_at     DATE
);

CREATE TABLE exercise_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id        BIGINT       NOT NULL REFERENCES grants(id),
    request_no      VARCHAR(40)  NOT NULL UNIQUE,
    quantity        NUMERIC(18,4) NOT NULL CHECK (quantity > 0),
    request_date    DATE         NOT NULL,
    status          VARCHAR(12)  NOT NULL CHECK (status IN ('PENDING','CONFIRMED','CANCELLED')),
    confirmed_date  DATE,
    cancelled_date  DATE
);

CREATE INDEX idx_nodes_grant ON vesting_nodes(grant_id, seq_no);
CREATE INDEX idx_requests_grant ON exercise_requests(grant_id);
